# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb582d5cf672427dcd33c1bdecd5984b"
application_url = "https://thousands-quoted-animation-sao.trycloudflare.com"
embedded = true
name = "Easy Promos"
handle = "learning-app-130"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts, read_discounts, read_products, write_products, read_purchase_options"

[auth]
redirect_urls = [
  "https://thousands-quoted-animation-sao.trycloudflare.com/auth/callback",
  "https://thousands-quoted-animation-sao.trycloudflare.com/auth/shopify/callback",
  "https://thousands-quoted-animation-sao.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
